services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 3
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example
    networks:
      - backend

  redis:
    image: redis:latest
    networks:
      - backend

  rev-proxy:
    depends_on:
      - wordpress
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - frontend


volumes:
  wordpress_data:
  db_data:

networks:
  frontend:
    driver: bridge
  backend: