services:
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - "80"
    environment:
      WORDPRESS_DATABASE_USER: user
      WORDPRESS_DATABASE_PASSWORD: password
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DATABASE_HOST: db
    deploy:
      replicas: 3
    expose:
      - 8080
    depends_on:
      - db
      - redis
    networks:
      - frontend
      - backend

  db:
    image: bitnami/mariadb:latest
    volumes:
      - ./data:/bitnami/mariadb
    ports:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    networks:
      - backend

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend

  rev-proxy:
    image: bitnami/nginx:latest
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge